### ISSUE TITLE
Error fetching icon data

### ISSUE THREAD

**Issue by aimergenge** [antfu/vscode-iconify#14]
Version: 0.2.2

I use unplugin-icons(perhaps not related):
```
export default defineConfig({
  plugins: [
    icons({
      // auto install icons when importing
      autoInstall: true,
      compiler: 'vue3',
      defaultClass: 'iconify',
    }),
    components({
      resolvers: [
        // auto import icons while using as component, combined with `autoInstall`
        iconsResolver({}),
      ]
    }),
  ],
})

```
use it in template like this:
```
<i-mdi-account-circle />
<i-mdi-light-alarm-plus />
```

error in console:
```
🈶 Activated, v0.2.2
🎛 108 icon sets loaded
☁️ [mdi] Downloading from https://raw.githubusercontent.com/iconify/collections-json/master/json//mdi.json
🐛 ERROR: Error: Request failed with status code 400
Error: Request failed with status code 400
	at createError (/Users/orange/.vscode/extensions/antfu.iconify-0.2.2/index.js:3323:19)
	at settle (/Users/orange/.vscode/extensions/antfu.iconify-0.2.2/index.js:3339:16)
	at IncomingMessage.handleStreamEnd (/Users/orange/.vscode/extensions/antfu.iconify-0.2.2/index.js:5044:15)
	at IncomingMessage.emit (events.js:327:22)
	at endReadableNT (internal/streams/readable.js:1327:12)
	at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

It seems the request url `https://raw.githubusercontent.com/iconify/collections-json/master/json//mdi.json` is wrong(double `/`)

which get the response:
```
<a href="/iconify/collections-json/master/json/mdi.json">Moved Permanently</a>.
```

**Comment by Thy3634** [comment]
I got the same issue. 
```
☁️ [mdi] Downloading from https://raw.githubusercontent.com/iconify/collections-json/master/json//mdi.json
🐛 ERROR: Error: getaddrinfo ENOENT raw.githubusercontent.com
Error: getaddrinfo ENOENT raw.githubusercontent.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
```

**Comment by likui628** [comment]
seems like https://github.com/antfu/vscode-iconify/issues/7
